version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      eslint-core:
        patterns:
          - "eslint"
          - "@eslint/js"
      jest:
        patterns:
          - "jest"
          - "@jest/globals"
          - "jest-environment-jsdom"
      mantine:
        patterns:
          - "@mantine/*"
      next:
        patterns:
          - "next"
          - "@next/eslint-plugin-next"
          - "eslint-config-next"
      prisma:
        patterns:
          - "prisma"
          - "@prisma/client"
      react-core:
        patterns:
          - "react"
          - "react-dom"
          - "react-test-renderer"
      react-types:
        patterns:
          - "@types/react"
          - "@types/react-dom"
      sentry:
        patterns:
          - "@sentry/*"
      tiptap:
        patterns:
          - "@tiptap/*"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
